title: "Jamie k – Game Developer Portfolio"
description: "Game programmer portfolio – gameplay, tools, and technical experiments."
baseurl: ""
url: "https://jamiek.cc"
theme: minima

author:
  name: "Jamie k"
  email: "koflerjamie@gmail.com"

# Social links (only if you have these)
github_username: GitJamieK
linkedin_username: jamie-kofler
